### PR TITLE
Remove unused imports

### PR DESCRIPTION
**Pull request by srawlins**

### CODE REVIEW

**Comment by jakemac53** [comment]
I am pretty sure these imports do actually have an effect, instead we should hide the warnings by adding an import prefix and then a doc comment elsewhere in the file which references that import prefix.

**Comment by srawlins** [comment]
Ah! I think I've hit your https://github.com/dart-lang/sdk/issues/22660 issue. The [docs for observe](https://pub.dartlang.org/packages/observe) make sense. I've added doc-comments as you suggested, and squashed commits. Thanks!

**Comment by jakemac53** [comment]
LGTM, do you need a release for this fix?

**Comment by srawlins** [comment]
No, I don't think so.

**Pull request merged**
